// <auto-generated />
using System;
using Attenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Attenda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413235219_RefactorGuestToPhoneNumber")]
    partial class RefactorGuestToPhoneNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<string>("ScannedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scanned_by");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_check_ins");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_check_ins_guest_id");

                    b.HasIndex("event_id")
                        .HasDatabaseName("ix_check_ins_event_id");

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapacityTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capacity_tier");

                    b.Property<string[]>("Celebrants")
                        .HasColumnType("text[]")
                        .HasColumnName("celebrants");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("GuestLimit")
                        .HasColumnType("integer")
                        .HasColumnName("guest_limit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("OrganizerName")
                        .HasColumnType("text")
                        .HasColumnName("organizer_name");

                    b.Property<string>("ReligiousAddress")
                        .HasColumnType("text")
                        .HasColumnName("religious_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VenueAddress")
                        .HasColumnType("text")
                        .HasColumnName("venue_address");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("GuestGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_group_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("RsvpStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rsvp_status");

                    b.Property<Guid>("RsvpToken")
                        .HasColumnType("uuid")
                        .HasColumnName("rsvp_token");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("GuestGroupId")
                        .HasDatabaseName("ix_guests_guest_group_id");

                    b.HasIndex("RsvpToken")
                        .IsUnique()
                        .HasDatabaseName("ix_guests_rsvp_token");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_guests_table_id");

                    b.HasIndex("event_id", "PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_guests_event_id_phone_number");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_groups");

                    b.HasIndex("event_id")
                        .HasDatabaseName("ix_guest_groups_event_id");

                    b.ToTable("guest_groups", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("event_id")
                        .HasDatabaseName("ix_tables_event_id");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_task_items");

                    b.HasIndex("event_id")
                        .HasDatabaseName("ix_task_items_event_id");

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("last4")
                        .IsFixedLength();

                    b.Property<string>("ProviderToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("UserId", "ProviderToken")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_methods_user_id_provider_token");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.CheckIn", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_ins_guests_guest_id");

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_check_ins_events_event_id");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.OwnsOne("Attenda.Domain.ValueObjects.EventDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_date");

                            b1.HasKey("EventId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("fk_events_events_id");
                        });

                    b.Navigation("Date")
                        .IsRequired();
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Guest", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", null)
                        .WithMany()
                        .HasForeignKey("GuestGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_guests_guest_groups_guest_group_id");

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_guests_tables_table_id");

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("Guests")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_guests_events_event_id");

                    b.OwnsMany("Attenda.Domain.ValueObjects.DietaryRestriction", "DietaryRestrictions", b1 =>
                        {
                            b1.Property<Guid>("guest_id")
                                .HasColumnType("uuid")
                                .HasColumnName("guest_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("restriction_name");

                            b1.HasKey("guest_id", "Id")
                                .HasName("pk_guest_dietary_restrictions");

                            b1.ToTable("guest_dietary_restrictions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("guest_id")
                                .HasConstraintName("fk_guest_dietary_restrictions_guests_guest_id");
                        });

                    b.Navigation("DietaryRestrictions");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("GuestGroups")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_guest_groups_events_event_id");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Table", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("Tables")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tables_events_event_id");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.TaskItem", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("TaskItems")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_task_items_events_event_id");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.PaymentMethod", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_methods_users_user_id");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("GuestGroups");

                    b.Navigation("Guests");

                    b.Navigation("Tables");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
