// <auto-generated />
using System;
using Attenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Attenda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416044218_AddInvitationSentToGuests")]
    partial class AddInvitationSentToGuests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScannedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("event_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GuestId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapacityTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capacity_tier");

                    b.Property<string[]>("Celebrants")
                        .HasColumnType("text[]")
                        .HasColumnName("celebrants");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("GuestLimit")
                        .HasColumnType("integer")
                        .HasColumnName("guest_limit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizerName")
                        .HasColumnType("text")
                        .HasColumnName("organizer_name");

                    b.Property<string>("ReligiousAddress")
                        .HasColumnType("text")
                        .HasColumnName("religious_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VenueAddress")
                        .HasColumnType("text")
                        .HasColumnName("venue_address");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("GuestGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InvitationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invitation_sent");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlusOnes")
                        .HasColumnType("integer");

                    b.Property<string>("PrivateNotes")
                        .HasColumnType("text")
                        .HasColumnName("private_notes");

                    b.Property<string>("RsvpStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RsvpToken")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.HasKey("Id");

                    b.HasIndex("GuestGroupId");

                    b.HasIndex("RsvpToken")
                        .IsUnique();

                    b.HasIndex("TableId");

                    b.HasIndex("EventId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("GuestGroups");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.PaymentPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscountCode")
                        .HasColumnType("text");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDiscount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentPackages");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .IsFixedLength();

                    b.Property<string>("ProviderToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProviderToken")
                        .IsUnique();

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.CheckIn", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.OwnsOne("Attenda.Domain.ValueObjects.EventDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_date");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("Attenda.Domain.ValueObjects.RsvpConfiguration", "RsvpConfig", b1 =>
                        {
                            b1.Property<Guid>("event_id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowDietaryRequirements")
                                .HasColumnType("boolean")
                                .HasColumnName("allow_dietary_requirements");

                            b1.Property<string>("ColorTheme")
                                .HasColumnType("text")
                                .HasColumnName("color_theme");

                            b1.Property<string>("HeaderImageUrl")
                                .HasColumnType("text")
                                .HasColumnName("header_image_url");

                            b1.Property<string>("Headline")
                                .HasColumnType("text")
                                .HasColumnName("headline");

                            b1.Property<string>("Message")
                                .HasColumnType("text")
                                .HasColumnName("message");

                            b1.Property<bool>("RequireAttendanceTracking")
                                .HasColumnType("boolean")
                                .HasColumnName("require_attendance_tracking");

                            b1.Property<string>("TypographyTheme")
                                .HasColumnType("text")
                                .HasColumnName("typography_theme");

                            b1.HasKey("event_id");

                            b1.ToTable("event_rsvp_configs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("event_id");
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("RsvpConfig");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Guest", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", null)
                        .WithMany()
                        .HasForeignKey("GuestGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Table", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Attenda.Domain.ValueObjects.DietaryRestriction", "DietaryRestrictions", b1 =>
                        {
                            b1.Property<Guid>("guest_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("restriction_name");

                            b1.HasKey("guest_id", "Id");

                            b1.ToTable("guest_dietary_restrictions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("guest_id");
                        });

                    b.Navigation("DietaryRestrictions");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.GuestGroup", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("GuestGroups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Table", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("Tables")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.TaskItem", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("TaskItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.PaymentMethod", b =>
                {
                    b.HasOne("Attenda.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("GuestGroups");

                    b.Navigation("Guests");

                    b.Navigation("Tables");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("Attenda.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
